cdrom: remove unused 'ret' variable
Avoid error while building with -Werror enabled

../govirt/ovirt-cdrom.c: In function ‘ovirt_cdrom_init_from_xml’:
../govirt/ovirt-cdrom.c:103:14: error: unused variable ‘ret’ [-Werror=unused-variable]
     gboolean ret = FALSE;
              ^~~

Signed-off-by: Eduardo Lima (Etrunko) <etrunko@redhat.com>